env:
  node: true
  commonjs: true
  es6: true
  browser: true
parser: babel-eslint
extends: 
  - airbnb
  - plugin:prettier/recommended
rules:
  react/jsx-filename-extension: 0 # react-native uses .js